#!/bin/bash

set_hosts() {
    local hostname="$1"    # Hostname/Domain
    local target_ip="$target"  # IP-Adresse aus der Umgebungsvariable

    if [[ -z "$target_ip" || -z "$hostname" ]]; then
        echo "Error: target IP is not set or Hostname is missing."
        echo "Usage: set-hosts <hostname>"
        return 1
    fi

    if grep -qE "^\s*$target_ip\s+$hostname" /etc/hosts; then
        echo "[*] Entry for $target_ip $hostname already exists."
    else
        echo "[*] Put $target_ip $hostname to /etc/hosts..."
        echo "$target_ip $hostname" | sudo tee -a /etc/hosts > /dev/null
        echo "[+] Entry added: $target_ip $hostname"
    fi
}

if [[ "$#" -eq 1 ]]; then
    set_hosts "$1"
else
    echo "Usage: $0 <hostname>"
    exit 1
fi
